@startuml
title Recherche d'un script - Diagramme d'activité

start
:Connexion utilisateur;
:Accès tableau de bord;
:Sélection "Recherche script";
:Saisie critères de recherche;

if (Résultat trouvé ?) then (oui)
  :Afficher script(s) trouvé(s);
  stop
else (non)
  :Afficher "Aucun script trouvé";
  stop
endif

@enduml